- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: true

- name: Ensure containerd configuration directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Check whether containerd config exists
  ansible.builtin.stat:
    path: /etc/containerd/config.toml
  register: containerd_config

- name: Generate default containerd configuration
  ansible.builtin.command:
    cmd: containerd config default
  register: containerd_default_config
  changed_when: false
  when: not containerd_config.stat.exists

- name: Write default containerd configuration
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_default_config.stdout }}\n"
    owner: root
    group: root
    mode: "0644"
  when: not containerd_config.stat.exists
  notify: Restart containerd

- name: Configure containerd to use systemd cgroup driver
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup\s*=\s*(?:true|false)\s*$'
    replace: '\1SystemdCgroup = true'
    backup: true
  notify: Restart containerd

- name: Ensure containerd is enable and running
  ansible.builtin.systemd_service:
    name: containerd
    enabled: true
    state: started



# Kubernetes APT repository

- name: Ensure apt keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Kubernetes repository signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.37/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: "0644"

- name: Convert Kubernetes repository key to GPG keyring
  ansible.builtin.command:
    cmd: >
      gpg --dearmor
      --yes
      --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      /tmp/kubernetes-release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Configure Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
      https://pkgs.k8s.io/core:/stable:/v1.37/deb/ /
    filename: kubernetes
    state: present

- name: Install cri-tools
  ansible.builtin.apt:
    name: cri-tools
    state: present
    update_cache: true

- name: Configure crictl
  ansible.builtin.copy:
    dest: /etc/crictl.yaml
    mode: "0644"
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 10
      debug: false

